version: "3.9"
   
services:
  
  web:
    build: ./crm
    env_file:
      - ./.env.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./crm:/usr/src/crm
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - PGUSER=postgres
      - POSTGRES_DB=crm_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=athena
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

    volumes:
    - ./nginx/frontend/static:/usr/share/nginx/html/static
  # frontend:
  #   build: ./unendlich
  #   depends_on:
  #     - web
  #   ports: 
  #     - 3000:3000
  #   volumes:
  #     - ./unendlich:/usr/src
  #     - /usr/src/node_modules


volumes:
  postgres_data:

