# pull official base image
FROM python:3.9.6-alpine

# set work directory
WORKDIR /usr/src/crm

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt ./

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY ./entrypoint.sh .

RUN sed -i 's/\r$//g' /usr/src/crm/entrypoint.sh
RUN chmod +x /usr/src/crm/entrypoint.sh

# copy project
COPY . .

ENTRYPOINT ["/usr/src/crm/entrypoint.sh"]
