# Generated by Django 3.2.16 on 2022-11-25 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PAST', 'PAST'), ('PROSPECTIVE', 'PROSPECTIVE')], default='PROSPECTIVE', max_length=100)),
                ('contact_info', models.CharField(max_length=12000)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=12000)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.account')),
            ],
        ),
    ]
