# Generated by Django 3.2.16 on 2022-11-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unendlich', '0002_alter_todo_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='name',
            new_name='label',
        ),
    ]
