# Generated by Django 4.1.3 on 2022-12-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unendlich', '0005_note_owner_notebook_owner_todo_owner_todolist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
